### PR TITLE
Give actionable advice when rustdoc JSON files fail to parse.

### LINKED ISSUE #105: Improve error message when failing to parse rustdoc output
Every so often, new Rust nightlies might cause the rustdoc JSON output format to change in a backward-incompatible way.

`cargo-semver-checks` will remain compatible with the most recent nightly's output, and we have a test that ensures that. However, users may still be using an older (or newer!) nightly that is incompatible with their `cargo-semver-checks` version.

If the JSON fails to parse, we should:
- check the nightly version to see if it's known to not work because it's too old (related: #88), then advise the user to upgrade to a newer nightly Rust
- otherwise, the nightly may be too new for the `cargo-semver-checks` version and we should advise the user to try upgrading to a newer `cargo-semver-checks` (as in #98)

### PR DESCRIPTION
**Pull request by obi1kenobi**
Resolves #105.

### CODE REVIEW

**Comment by obi1kenobi** [comment]
@epage would you say this is also sufficient for #88 or did you have something else in mind for that one? I wasn't sure if information about which nightly ranges use which rustdoc format versions is available somewhere, for example.

File: src/util.rs [hunk 1]
```diff
@@ -16,8 +22,69 @@ pub(crate) fn load_rustdoc_from_file(path: &Path) -> anyhow::Result<Crate> {
...
+                        both cargo-semver-checks and Rust nightly, \
+                        which should always be compatible with each other.",
+                        rustdoc_types::FORMAT_VERSION,
+                        version.format_version,
+                    )
+                }
+                std::cmp::Ordering::Greater => {
+                    // The error here is case (3).
+                    bail!(
+                        "Failed to parse rustdoc JSON file: {path:?}\n\n\
```
Comment (epage) [inline src/util.rs:66]: As a reviewer, escaped newlines make it harder to review the legibility of these error messages.

File: src/util.rs [hunk 2]
```diff
@@ -16,8 +22,69 @@ pub(crate) fn load_rustdoc_from_file(path: &Path) -> anyhow::Result<Crate> {
...
+                        This version of cargo-semver-checks requires rustdoc JSON version {0}, \
+                        but the JSON file uses the newer version {1}.\n\n\
```
Comment (epage) [inline src/util.rs:68]: I feel like these messages could be more concise so the user can more easily find the information they need.

Something like
```
rustdoc output is too new (version {}) for cargo-semver-checks when parsing {}

note: a newer version of cargo-semver-checks is likely available
```
- cargo's style guide says to not capitalize error messages
- rustc's style guide says to avoid "did you mean" or "suggestions" but to instead offer people alternatrives (ie be less prescriptive) which is why I made it a "note:".  cargo doesn't follow this atm but I suspect we should conform to it.

File: src/util.rs [hunk 3]
```diff
@@ -16,8 +22,69 @@ pub(crate) fn load_rustdoc_from_file(path: &Path) -> anyhow::Result<Crate> {
...
+            // Several possible options and their resolutions:
+            // (1) The file isn't actually a rustdoc JSON file. The user should supply a valid file.
+            // (2) The rustdoc JSON file has a version number that is too old, and isn't supported.
+            //     The user should upgrade to a newer nightly Rust version and regenerate the file.
+            // (3) The rustdoc JSON file has a version number that is too new, and isn't supported.
+            //     The user should attempt to upgrade to a newer cargo-semver-checks version
+            //     if one is already available, or open a GitHub issue otherwise.
+
+            // The error on this line is case (1).
+            let version = serde_json::from_str::<RustdocFormatVersion>(&s).with_context(|| {
```
Comment (epage) [inline src/util.rs:38]: > @epage would you say this is also sufficient for https://github.com/obi1kenobi/cargo-semver-check/issues/88 or did you have something else in mind for that one? I wasn't sure if information about which nightly ranges use which rustdoc format versions is available somewhere, for example.

The core of #88 is the install instructions.

Something to keep in mind is some users might be stuck on a specific nightly version
- Ideally, we'd let them know what range of versions work rather than just saying "use latest"
- Ideally, they'd have a path for finding what older version would work

While the error reporting is good and important, the reason the documentation is important is that an error is a road bump and the more road bumps someone hits to accomplishing their task, the more frustrated they get.  #88 is about avoiding that.

File: src/util.rs [hunk 4]
```diff
@@ -16,8 +22,69 @@ pub(crate) fn load_rustdoc_from_file(path: &Path) -> anyhow::Result<Crate> {
...
+                format!(
+                    "Failed to parse the rustdoc JSON file, and could not determine its \
+                    format version. Are you sure this is a valid rustdoc JSON file? \
+                    File path: {:?}",
+                    path
```
[the remark this answers is not in the document]
Comment (obi1kenobi) [reply src/util.rs:43]: `Path` isn't `Display`, and its `Debug` implementation just prints the path in quotes. This is what the errors currently look like:
image

Is there a way to turn this `Path` value into something that is `Display`? I know my path handling is sloppy :)

[the remark this answers is not in the document]
Comment (epage) [reply src/util.rs:43]: `path.display()`

File: src/util.rs (hunk 1 above)
Comment (obi1kenobi) [reply src/util.rs:66]: There's a bit of tension here and I'm not sure how to navigate it:
- If I use unescaped newlines and omit the trailing `\`, then the Rust string contains 24 spaces' worth of indentation which is not removed.
- If I escape the newlines and used a trailing `\`, then there's no indentation in the final string but as you point out, the legibility is not ideal.

One hybrid option is something like this:
```rust
bail!(
    "rustdoc output format is too old (v{1}, need v{0}) for file \
    {path:?}\n\n\
    \
    note: Using a newer Rust nightly version should help. \
    The latest cargo-semver-checks and Rust nightly should always be \
    compatible with each other.",
    rustdoc_types::FORMAT_VERSION,
    version.format_version,
)
```

Is that preferable?

File: src/util.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (obi1kenobi) [reply src/util.rs:43]: I didn't realize that was a thing, I thought you had meant the trait. Thanks for bearing with me. Fixed!

File: src/util.rs (hunk 2 above)
Comment (obi1kenobi) [reply src/util.rs:68]: I tried my hand at mirroring your style, let me know if this is better.

File: src/util.rs (hunk 1 above)
Comment (epage) [reply src/util.rs]: Personally, I wouldn't indent it.

Getting fancy with escapes means you are artificially making the format look like the real thing which can drift apart.

I would put this as non-blocking to be clear.

File: src/util.rs [hunk 5]
```diff
@@ -1,23 +1,91 @@
...
+            // (2) The rustdoc JSON file has a version number that is too old, and isn't supported.
+            //     The user should upgrade to a newer nightly Rust version and regenerate the file.
+            // (3) The rustdoc JSON file has a version number that is too new, and isn't supported.
+            //     The user should attempt to upgrade to a newer cargo-semver-checks version
+            //     if one is already available, or open a GitHub issue otherwise.
+
+            // The error on this line is case (1).
+            let version = serde_json::from_str::<RustdocFormatVersion>(&s).with_context(|| {
+                format!(
+                    "parsing rustdoc JSON failed, and could not determine rustdoc format version \
```
Comment (epage) [inline src/util.rs:40]: nit: Personally, I would leave out "and could not determine rustdoc format version", that is an implementation detail that the user can't act upon.

As hybrid, you could instead make it "Unrecognized rustdoc output" or something

File: src/util.rs [hunk 6]
```diff
@@ -1,23 +1,91 @@
...
+            match version.format_version.cmp(&rustdoc_types::FORMAT_VERSION) {
+                std::cmp::Ordering::Less => {
+                    // The error here is case (2).
+                    bail!(
+                        "rustdoc output format is too old (v{1}, need v{0}) for file \
+                        {2}\n\n\
+                        \
+                        note: Using a newer Rust nightly version should help. \
+                        The latest cargo-semver-checks and Rust nightly should always be \
+                        compatible with each other.",
```
Comment (epage) [inline src/util.rs:55]: nit: this feels superfluous

File: src/util.rs [hunk 7]
```diff
@@ -1,23 +1,91 @@
...
+                }
+                std::cmp::Ordering::Greater => {
+                    // The error here is case (3).
+                    bail!(
+                        "rustdoc output format is too new (v{1}, need v{0}) for this \
+                        cargo-semver-checks when parsing {2}\n\n\
+                        \
+                        note: A newer version of cargo-semver-checks is likely available. \
+                        The latest cargo-semver-checks and Rust nightly should always be \
+                        compatible with each other.",
```
Comment (epage) [inline src/util.rs:69]: nit: this feels superfluous

File: src/util.rs [hunk 8]
```diff
@@ -1,23 +1,91 @@
...
+                        rustdoc_types::FORMAT_VERSION,
+                        version.format_version,
+                        path.display(),
+                    )
+                }
+                std::cmp::Ordering::Equal => Err(e).with_context(|| {
+                    format!(
+                        "parsing rustdoc failed even though the format was the expected \
+                            version (v{}) for file {}\n\n\
```
Comment (epage) [inline src/util.rs:78]: Nit: To put this more in user terms what about `Unexpected parse error for v{} rustdoc file: {}`?

File: src/util.rs [hunk 9]
```diff
@@ -1,23 +1,91 @@
...
+                        rustdoc_types::FORMAT_VERSION,
+                        version.format_version,
+                        path.display(),
+                    )
+                }
+                std::cmp::Ordering::Greater => {
+                    // The error here is case (3).
+                    bail!(
+                        "rustdoc output format is too new (v{1}, need v{0}) for this \
+                        cargo-semver-checks when parsing {2}\n\n\
```
Comment (epage) [inline src/util.rs:65]: nit: "for this cargo-semver-checks" is superfluous and sounds a bit strange

**Review by epage — APPROVED** [review]
